### ISSUE TITLE
bug: the `npx` command doesn't work

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#2694]
The following command should work

```bash
npx @tailcallhq/tailcall init
npm error could not determine executable to run

npm error A complete log of this run can be found in: /Users/tushar/.npm/_logs/2024-08-14T15_29_24_044Z-debug-0.log
```

```
0 verbose cli /Users/tushar/.nvm/versions/node/v20.15.1/bin/node /Users/tushar/.nvm/versions/node/v20.15.1/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@10.7.0
2 info using node@v20.15.1
3 silly config:load:file:/Users/tushar/.nvm/versions/node/v20.15.1/lib/node_modules/npm/npmrc
4 silly config:load:file:/Users/tushar/Documents/Projects/type-tango/.npmrc
5 silly config:load:file:/Users/tushar/.npmrc
6 silly config:load:file:/Users/tushar/.nvm/versions/node/v20.15.1/etc/npmrc
7 verbose title npm exec @tailcallhq/tailcall init
8 verbose argv "exec" "--" "@tailcallhq/tailcall" "init"
9 verbose logfile logs-max:10 dir:/Users/tushar/.npm/_logs/2024-08-14T15_28_01_970Z-
10 verbose logfile /Users/tushar/.npm/_logs/2024-08-14T15_28_01_970Z-debug-0.log
11 silly logfile start cleaning logs, removing 1 files
12 silly logfile done cleaning log files
13 http fetch GET 200 https://registry.npmjs.org/@tailcallhq%2ftailcall 406ms (cache revalidated)
14 verbose stack Error: could not determine executable to run
14 verbose stack     at getBinFromManifest (/Users/tushar/.nvm/versions/node/v20.15.1/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
14 verbose stack     at exec (/Users/tushar/.nvm/versions/node/v20.15.1/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:183:15)
14 verbose stack     at async module.exports (/Users/tushar/.nvm/versions/node/v20.15.1/lib/node_modules/npm/lib/cli/entry.js:74:5)
15 verbose pkgid @tailcallhq/tailcall@0.104.0
16 verbose cwd /Users/tushar/Documents/Projects/type-tango
17 verbose Darwin 23.4.0
18 verbose node v20.15.1
19 verbose npm  v10.7.0
20 error could not determine executable to run
21 verbose exit 1
22 verbose code 1
23 error A complete log of this run can be found in: /Users/tushar/.npm/_logs/2024-08-14T15_28_01_970Z-debug-0.log
```

**Comment by webbdays** [comment]
@tusharmath

**Comment by tusharmath** [comment]
@webbdays The latest version throws this error — 

```
npx --verbose  @tailcallhq/tailcall init
npm verbose cli /Users/tushar/.nvm/versions/node/v20.15.1/bin/node /Users/tushar/.nvm/versions/node/v20.15.1/lib/node_modules/npm/bin/npm-cli.js
npm info using npm@10.7.0
npm info using node@v20.15.1
npm verbose title npm exec @tailcallhq/tailcall init
npm verbose argv "exec" "--loglevel" "verbose" "--" "@tailcallhq/tailcall" "init"
npm verbose logfile logs-max:10 dir:/Users/tushar/.npm/_logs/2024-09-26T08_19_20_356Z-
npm verbose logfile /Users/tushar/.npm/_logs/2024-09-26T08_19_20_356Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/@tailcallhq%2ftailcall 310ms (cache revalidated)
npm verbose stack Error: could not determine executable to run
npm verbose stack     at getBinFromManifest (/Users/tushar/.nvm/versions/node/v20.15.1/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
npm verbose stack     at exec (/Users/tushar/.nvm/versions/node/v20.15.1/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:183:15)
npm verbose stack     at async module.exports (/Users/tushar/.nvm/versions/node/v20.15.1/lib/node_modules/npm/lib/cli/entry.js:74:5)
npm verbose pkgid @tailcallhq/tailcall@0.115.0
npm verbose cwd /Users/tushar/Documents/Projects/tailcall
npm verbose Darwin 23.4.0
npm verbose node v20.15.1
npm verbose npm  v10.7.0
npm error could not determine executable to run
npm verbose exit 1
npm verbose code 1

npm error A complete log of this run can be found in: /Users/tushar/.npm/_logs/2024-09-26T08_19_20_356Z-debug-0.log
```

**Comment by webbdays** [comment]
looking into it.

**Comment by webbdays** [comment]
@tusharmath 
can i know the package version this code was deployed.

**Comment by webbdays** [comment]
I think new package is not published.

**Comment by webbdays** [comment]
version: 0.115.0 doest have new install scripts.

**Comment by webbdays** [comment]
@tusharmath 
any issue publishing new package.

**Comment by webbdays** [comment]
https://github.com/tailcallhq/tailcall/releases/download/vv0.115.3/tailcall-x86_64-unknown-linux-gnu
while deploying version is used as v0.115.3 instead of 0.115.3

**Comment by webbdays** [comment]
A step to test npm package before publish is good to have. To avoid affecting users.
